import {api,authorize,Connection} from './network.js';
const portalIdentity=await authorize();
import{Match,VIEW_W,VIEW_H,POWER_RULES}from'./simulation.js';import{Renderer}from'./renderer.js';
const $=id=>document.getElementById(id),canvas=$('game'),renderer=new Renderer(canvas);let match=new Match(),size=3,state='start',keys=new Set(),shoot=false,last=0,accumulator=0,noticeTimer=0,muted=true,audio=null;const input={};let online=false,myId=0,currentCode='',lobby=null,ready=false,sendClock=0;
try{$('nickname').value=localStorage.getItem('nfg.nickname')||'Você'}catch{}
function sound(type){if(muted)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.connect(g);g.connect(audio.destination);o.type=type==='hit'?'triangle':'sine';o.frequency.setValueAtTime(type==='point'?720:type==='hit'?180:440,audio.currentTime);o.frequency.exponentialRampToValueAtTime(type==='point'?1100:100,audio.currentTime+.1);g.gain.setValueAtTime(.035,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.15);o.start();o.stop(audio.currentTime+.16)}catch{muted=true}}
function resetInput(){keys.clear();shoot=false;input.coffee=false;input.pickup=false;input.super=false}
function showNotice(text){$('notice').textContent=text;$('notice').classList.add('visible');noticeTimer=2.2}
function sync(){const p=match.players[0];$('blueScore').textContent=String(match.score[0]).padStart(2,'0');$('greenScore').textContent=String(match.score[1]).padStart(2,'0');const t=Math.ceil(Math.max(0,match.time));$('timer').textContent=`${String(Math.floor(t/60)).padStart(2,'0')}:${String(t%60).padStart(2,'0')}`;$('phase').textContent=match.overtime?'PRORROGAÇÃO':online?'ONLINE':'TREINO';$('healthText').textContent=`${p.hp} / 100`;$('healthBar').style.width=p.hp+'%';$('coffeeCount').textContent='× '+p.coffee;$('coffeeSlot').style.opacity=p.coffee?1:.45;$('fireTime').textContent=p.dead>0?'AGUARDE RETORNAR':p.fireCooldown>0?Math.ceil(p.fireCooldown)+'s':'Q · PRONTO';$('firePower').classList.toggle('powered',p.fireCooldown<=0&&p.dead<=0);for(const type of ['speed','double']){const el=$(type+'Power'),remaining=p.powers[type];el.classList.toggle('powered',remaining>0);$(type+'Time').textContent=remaining>0?Math.ceil(remaining)+'s':'PEGUE NO MAPA';}$('personalStats').textContent=state==='start'?'EQUIPE AZUL · PRONTO PARA O EXPEDIENTE':`${p.kills} PONTOS · ${p.deaths} QUEDAS · EQUIPE ${p.team?'VERDE':'AZUL'}`;}
function start(){connection.close();online=false;myId=0;const name=$('nickname').value.trim().slice(0,16)||'Você';try{localStorage.setItem('nfg.nickname',name)}catch{}match=new Match(size,name);match.players[0].local=true;state='playing';accumulator=0;resetInput();$('startScreen').hidden=true;$('resultScreen').hidden=true;$('pauseScreen').hidden=true;$('leave').hidden=false;$('playerName').textContent=name.toUpperCase();$('modeLabel').textContent=`${size}×${size} · Treino com bots`;$('game').focus({preventScroll:true});renderer.camera.follow(match.players[0]);showNotice('Valendo! Passe nos poderes ϟ e ×2 para ativá-los.');sync();}
function home(){connection.close();online=false;$('lobbyScreen').hidden=true;state='start';resetInput();match=new Match(size);$('startScreen').hidden=false;$('pauseScreen').hidden=true;$('resultScreen').hidden=true;$('leave').hidden=true;$('notice').classList.remove('visible');$('playerName').textContent='VOCÊ';sync();}
function pause(){if(state!=='playing')return;if(online){resetInput();connection.send({type:'input',input:{}});return}state='paused';resetInput();$('pauseScreen').hidden=false;$('resume').focus();}
function resume(){if(state!=='paused')return;state='playing';resetInput();$('pauseScreen').hidden=true;canvas.focus({preventScroll:true});}
function finish(){state='finished';resetInput();const p=match.players[0],a=match.score[0],b=match.score[1];$('resultTitle').textContent=a===b?'Deu empate!':a>b?'Vitória azul!':'Vitória verde!';$('resultText').textContent=`Azul ${a} × ${b} Verde. ${a>b?'O escritório é de vocês.':a<b?'Mais uma? A próxima pode ser sua.':'Equipes à altura. Que tal uma revanche?'}`;$('stats').replaceChildren(...[[p.kills,'Seus pontos'],[p.deaths,'Suas quedas']].map(([n,label])=>{const el=document.createElement('div'),strong=document.createElement('b');strong.textContent=n;el.append(strong,document.createTextNode(label));return el}));$('resultScreen').hidden=false;$('again').focus();sound('point')}
document.querySelectorAll('[data-size]').forEach(b=>{b.setAttribute('aria-pressed',b.dataset.size==='3');b.onclick=()=>{size=Number(b.dataset.size);document.querySelectorAll('[data-size]').forEach(x=>{x.classList.toggle('selected',x===b);x.setAttribute('aria-pressed',x===b)});match=new Match(size);sync()}});
$('start').onclick=start;$('again').onclick=()=>{if(online){$('resultScreen').hidden=true;state='lobby';$('lobbyScreen').hidden=false;renderLobby()}else start()};$('back').onclick=home;$('quit').onclick=home;$('resume').onclick=resume;$('leave').onclick=()=>{if(online)home();else pause()};
let resumeAfterHelp=false;$('help').onclick=()=>{resumeAfterHelp=state==='playing';pause();$('helpDialog').showModal()};function closeHelp(){$('helpDialog').close()}$('closeHelp').onclick=closeHelp;$('understood').onclick=closeHelp;$('helpDialog').addEventListener('close',()=>{if(resumeAfterHelp)resume();resumeAfterHelp=false});
$('sound').onclick=()=>{muted=!muted;$('sound').textContent=muted?'Som desligado':'Som ligado';$('sound').setAttribute('aria-label',muted?'Ativar som':'Desativar som');$('sound').setAttribute('aria-pressed',String(!muted));if(!muted)sound('point')};
window.addEventListener('keydown',e=>{if($('helpDialog').open)return;if(e.code==='Escape'){if(online){resetInput();showNotice('A partida online continua. Use Sair da partida para sair.');return}if(state==='playing')pause();else if(state==='paused')resume();return}if(state!=='playing'||/INPUT|TEXTAREA/.test(e.target.tagName))return;if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','KeyW','KeyA','KeyS','KeyD','KeyE','KeyQ'].includes(e.code)){e.preventDefault();keys.add(e.code);if(!e.repeat&&e.code==='Space')input.coffee=true;if(!e.repeat&&e.code==='KeyE')input.pickup=true;if(!e.repeat&&e.code==='KeyQ')input.super=true}});
window.addEventListener('keyup',e=>keys.delete(e.code));window.addEventListener('blur',pause);document.addEventListener('visibilitychange',()=>{if(document.hidden)pause()});
canvas.addEventListener('pointermove',e=>{const rect=canvas.getBoundingClientRect();const scale=Math.min(rect.width/VIEW_W,rect.height/VIEW_H);const offsetX=(rect.width-VIEW_W*scale)/2,offsetY=(rect.height-VIEW_H*scale)/2;renderer.aim.x=(e.clientX-rect.left-offsetX)/scale;renderer.aim.y=(e.clientY-rect.top-offsetY)/scale});canvas.addEventListener('pointerdown',e=>{if(e.button===0&&state==='playing'){shoot=true;canvas.focus();canvas.setPointerCapture(e.pointerId);e.preventDefault()}});window.addEventListener('pointerup',()=>shoot=false);canvas.addEventListener('lostpointercapture',()=>shoot=false);canvas.addEventListener('contextmenu',e=>e.preventDefault());
function frame(now){const dt=Math.min((now-last)/1000||0,.05);last=now;if(online&&state==='playing'){sendClock+=dt;if(sendClock>=1/30){sendClock=0;input.left=keys.has('KeyA')||keys.has('ArrowLeft');input.right=keys.has('KeyD')||keys.has('ArrowRight');input.up=keys.has('KeyW')||keys.has('ArrowUp');input.down=keys.has('KeyS')||keys.has('ArrowDown');input.fire=shoot;const p=match.players[0];renderer.camera.follow(p);const aim=renderer.camera.toWorld(renderer.aim.x,renderer.aim.y);input.angle=Math.atan2(aim.y-p.y,aim.x-p.x);connection.send({type:'input',input});input.coffee=false;input.pickup=false;input.super=false;}sync();}else if(state==='playing'){accumulator+=dt;while(accumulator>=1/60&&state==='playing'){input.left=keys.has('KeyA')||keys.has('ArrowLeft');input.right=keys.has('KeyD')||keys.has('ArrowRight');input.up=keys.has('KeyW')||keys.has('ArrowUp');input.down=keys.has('KeyS')||keys.has('ArrowDown');input.fire=shoot;const p=match.players[0];renderer.camera.follow(p);const aim=renderer.camera.toWorld(renderer.aim.x,renderer.aim.y);input.angle=Math.atan2(aim.y-p.y,aim.x-p.x);match.tick(1/60,input);input.coffee=false;input.pickup=false;input.super=false;for(const event of match.events){if(event.type==='point'){const owner=match.players.find(x=>x.id===event.player);showNotice(`${owner.name} marcou para a equipe ${owner.team?'verde':'azul'}!`);sound('point')}if(event.type==='power'&&event.player===0){showNotice(`${POWER_RULES[event.power].name} ativado! ${POWER_RULES[event.power].duration} segundos.`);sound('point')}if(event.type==='fireball'&&event.player===0){showNotice('Bola de fogo! Recarga de 12 segundos.');sound('hit')}if(event.type==='overtime')showNotice('Prorrogação! O próximo ponto decide.');if(event.player===0&&['throw','hit'].includes(event.type))sound(event.type);if(event.player===0&&event.type==='pickup')showNotice('Café na mão! Use Espaço para derramar.')};accumulator-=1/60;if(match.finished)finish()}sync();if(noticeTimer>0){noticeTimer-=dt;if(noticeTimer<=0)$('notice').classList.remove('visible')}}renderer.draw(match,state==='playing',state==='start');requestAnimationFrame(frame)}

function renderLobby(){
 if(!lobby)return;$('lobbyCode').textContent=currentCode;$('lobbyInfo').textContent=`${lobby.size}×${lobby.size} · ${lobby.members.length}/${lobby.size*2} jogadores`;
 $('roster').replaceChildren(...lobby.members.map(m=>{const row=document.createElement('div');row.textContent=`${m.team?'🟢':'🔵'} ${m.name}${m.id===myId?' (você)':''} · ${m.ready?'Pronto':'Aguardando'}`;return row}));
 ready=lobby.members.find(m=>m.id===myId)?.ready||false;$('ready').textContent=ready?'Cancelar pronto':'Estou pronto';
 $('startOnline').hidden=lobby.host!==portalIdentity.user;$('startOnline').disabled=lobby.members.length!==lobby.size*2||!lobby.members.every(m=>m.ready);
}
const connection=new Connection(msg=>{
 if(msg.type==='welcome'){myId=msg.id;currentCode=msg.code;online=true;state='lobby';$('startScreen').hidden=true;$('lobbyScreen').hidden=false;$('leave').hidden=false;}
 if(msg.type==='lobby'){lobby=msg;renderLobby()}
 if(msg.type==='started'){state='playing';resetInput();$('lobbyScreen').hidden=true;$('resultScreen').hidden=true;canvas.focus();$('modeLabel').textContent=`Sala ${currentCode} · Online`;}
 if(msg.type==='snapshot'){
  const wasFinished=match.finished;match=msg.state;match.players.sort((a,b)=>(a.id===myId?-1:b.id===myId?1:a.id-b.id));for(const p of match.players)p.local=p.id===myId;
  $('playerName').textContent=match.players[0].name.toUpperCase();
  if(!match.finished){state='playing';$('lobbyScreen').hidden=true;}
  for(const e of match.events||[]){if(e.type==='point')sound('point');if(e.type==='hit'&&e.player===myId)sound('hit')}
  if(match.finished&&!wasFinished){finish();$('again').textContent='Voltar à sala ↗';}
 }
 if(msg.type==='error')$('lobbyError').textContent=msg.error;
 if(msg.type==='cancelled'){state='lobby';resetInput();$('lobbyScreen').hidden=false;$('resultScreen').hidden=true;$('lobbyError').textContent=msg.error;}
},()=>{if(online){home();$('onlineError').textContent='Conexão encerrada. Entre novamente com o código; confirme que sua sessão está ativa.';}});
async function join(code){
 code=code.trim().toUpperCase();if(!/^[A-F0-9]{10}$/.test(code))throw new Error('Informe o código de 10 caracteres.');
 $('onlineError').textContent='Conectando…';await connection.connect(code);$('onlineError').textContent='';
}
$('createRoom').onclick=async()=>{const b=$('createRoom');b.disabled=true;try{const r=await api('/rooms',{size});await join(r.code)}catch(e){$('onlineError').textContent=e.message}finally{b.disabled=false}};
$('joinRoom').onclick=async()=>{const b=$('joinRoom');b.disabled=true;try{await join($('roomCode').value)}catch(e){$('onlineError').textContent=e.message}finally{b.disabled=false}};
$('ready').onclick=()=>connection.send({type:'ready',ready:!ready});$('startOnline').onclick=()=>connection.send({type:'start'});$('leaveLobby').onclick=home;
$('copyInvite').onclick=async()=>{const url=new URL(location.href);url.search='';url.searchParams.set('sala',currentCode);try{await navigator.clipboard.writeText(url.href);$('copyInvite').textContent='Convite copiado!'}catch{$('lobbyError').textContent='Código da sala: '+currentCode}};
const invite=new URLSearchParams(location.search).get('sala');if(invite)$('roomCode').value=invite.toUpperCase();
$('nickname').value=portalIdentity.name||portalIdentity.user;
setInterval(async()=>{try{const access=await api('/access');if(!access.unlocked){connection.close();location.reload()}}catch{connection.close();location.reload()}},30000);
sync();requestAnimationFrame(frame);
